packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true

overrides:
  devalue: '>=5.8.1'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  serialize-javascript@<=7.0.2: '>=7.0.3'

minimumReleaseAge: 4320
blockExoticSubdeps: true
strictDepBuilds: true
